<?php

namespace Locapp\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BiensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiensRepository extends EntityRepository
{
}
