loc_app_web:
    resource: "@LocAppWebBundle/Resources/config/routing.yml"
    prefix:   /

loc_app_user:
    resource: "@LocAppUserBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:   /login
    defaults:  { _controller: LocAppUserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

