locapp_main:
    resource: "@LocappMainBundle/Resources/config/routing.yml"
    prefix:   /

locapp_users:
    resource: "@LocappUsersBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:   /login
    defaults:  { _controller: LocappUsersBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

